### ISSUE TITLE
SAM excluding floor and roof

### ISSUE THREAD

**Issue by michalinadengusiak** [HoareLea/SAM#28] opened 2020-03-08 15:05 UTC
Hi! I was testing SAM, and tried creating a building in it and then when SAM only selected the Walls I knew something was wrong so I checked it.
 As you can see before the SAM Topologic everything is selected, however afterwards it just ignores the Roof and Floor. I think this is a bug yet if I made a mistake please correct me!

![SAM_No_RoofFloor](https://user-images.githubusercontent.com/37042279/76161983-e66a2400-6138-11ea-810b-b1df532cceaa.jpg)

This is my zip file:
[SAM_No_RoofFloor.zip](https://github.com/HoareLea/SAM/files/4303357/SAM_No_RoofFloor.zip)

Thanks,
Michalina

**Comment by michaldengusiak** [comment] 2020-03-09 11:09
@michalinadengusiak 
thanks for finding bug

the issue is to do with Topologic function we use IsInside, currently, we use this method and is not perfect I implemented temporary solution but we decided to use our own engine to do mapping
![image](https://user-images.githubusercontent.com/26113670/76207378-943b0880-61f5-11ea-816b-6821b41fb6fd.png)


we implemented a temp solution and used 
`Topologic.Utilities.FaceUtility.InternalVertex` but this method is slow and sometimes does not find a point, once we have our geometry engine we will replace with our method
![image](https://user-images.githubusercontent.com/26113670/76207754-44107600-61f6-11ea-864a-7a6431855fc8.png)

**Comment by michaldengusiak** [comment] 2020-03-10 11:04
this is now transferred to SAM methods so should work much faster

**Closed by michaldengusiak** 2020-03-10 11:04 UTC
